config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/mobile'


  resources :users, :recipes
  post 'reservations/new' => 'charges/new', as: 'new_charge'

  get 'users/user_account'
  get 'users/my_reservations_user'
  get 'login_user' => 'sessions#new_user'

  get 'chefs/chef_account'
  # get 'chefs/my_reservations_chef'
  get 'login_chef' => 'sessions#new_chef'

  get 'messages/new'

  get 'reservations/new'

  post 'sessions/login_user'
  post 'sessions/login_chef'



  resources :reservations do
    resources :messages
  end
  get 'reservations/show'
  patch 'reservations/show'


  post 'chefs' => 'chefs#create'
  get 'chefs' => 'chefs#index', as: 'chefs_admin'
  get 'chefs/new' => 'chefs#new', as: 'new_chef'
  get 'chefs/:id/account' => 'chefs#show', as: 'chef'
  get 'chefs/:id/edit' => 'photos#edit', as: 'edit_chef'
  patch 'chefs/:id' => 'chefs#update'
  put 'chefs/:id' => 'chefs#update'
  delete 'chefs/:id' => 'chefs#destroy'
  get 'chefs/:id' => 'chefs#toggle', as: 'toggle_active_chef'

  get '/logout', to: 'sessions#destroy'

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_secure_password
  has_many :reservations
  has_many :messages
  after_initialize :init
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, uniqueness: true
  validates_format_of :phone, :with => /\A(1?(?: |\-|\.)?(?:\(\d{3}\)|\d{3})(?: |\-|\.)?\d{3}(?: |\-|\.)?\d{4})\z/, message: "bad format ex. 555-555-5555"
  # validates :password_digest#, confirmation: true
  # validates :password_digest_confirmation, presence: true

  def init
    self.active = false if (self.has_attribute? :active) && self.active.nil?
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :show, :update]
  before_action :require_chef, only:[:edit,:show,:update]
  before_action :is_admin?, only: [:index,:toggle]

  def index
    @chefs_inactive = Chef.where(active:false)
    @chefs_active = Chef.where(active:true)
  end
  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new chef_params
    if @chef.save
      session[:chef_id] = @chef.id
      # ChefMailer.welcome_email(@chef).deliver
      redirect_to reservations_path, flash:{notice: 'Created chef and logged in'}
    else
      render action: 'new', flash:{notice: 'Please try again'}
    end
  end

  def edit
    @profile = current_chef
  end

  def show
    @chef_old_confirmations = Reservation.chef_old(current_chef)
    @chef_confirmations = Reservation.chef(current_chef)
    @chef_reservations = Reservation.available
    @profile = @chef
  end
  def update
    @chef = Chef.
        find_by(email: @chef[:email]).
        try(:authenticate, chef_params[:old_password])
    if @chef
      if @chef.update(chef_params.except(:old_password))
        redirect_to @chef, notice: 'Chef was successfully updated'
      else
        redirect_to :back, notice: 'something went wrong'
      end
    else
      redirect_to :back, notice: 'Your old password was wrong'
    end
  end
  def toggle
    @chef = Chef.find(chef_id_params[:id])
    @chef.active = !@chef.active
    @chef.save
    redirect_to :back, notice: "Chef's availability has changed"
  end
  private
  def set_chef
    @chef = current_chef
  end
  def chef_id_params
    params.permit(:id)
  end
  def chef_params
    params.
    require(:chef).
    permit(:email, :password,:first_name, :last_name, :password_confirmation, :city, :state, :zip, :phone, :old_password,:id)
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/chefsign.slim
.row
  .form-wrapper
    .large-6.columns
      .signup-panel
        p.welcome Chef Sign In
        = form_tag sessions_create_chef_path do |f|
          form
            .row.collapse
              .small-10.columns
                = label_tag :email
                = text_field_tag :email
            .row.collapse
            .row.collapse
              .small-10.columns
                = label_tag :password
                = password_field_tag :password
            .row.collapse
              .small-10.columns
                = submit_tag 'Log in'

app/views/chefs/edit.slim
= render 'home/profile'

app/views/chefs/index.slim
.chefs
  - if @chefs_inactive.count > 0
    h1 inactive chefs
    .chefs-inactive
      - @chefs_inactive.each do |chef|
        = div_for(chef, class: 'inactive_chef') do
          h3 Chef: #{chef.first_name}
          = link_to "toggle active", toggle_active_chef_path(chef.id)
.chefs-active
  h1 active chefs
  - @chefs_active.each do |chef|
    = div_for(chef, class: 'active_chefs') do
      h3 Chef: #{chef.first_name}
      = link_to "toggle active", toggle_active_chef_path(chef.id)

app/views/chefs/new.html.slim
p New Chef
= simple_form_for @chef do |f|
      = f.input :email
      = f.input :first_name
      = f.input :last_name
      = f.input :address
      = f.input :address2
      = f.input :city
      = f.input :state
      = f.input :zip
      = f.input :phone, as: :tel
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit
p
  | Already have an account?
  == link_to "Login Here ", sessions_login_chef_path

app/views/chefs/new.slim
.row
  .large-6.columns
    .signup-panel
      p.welcome New Chef
      = simple_form_for @chef do |f|
        form
          .row.collapse
            .small-2.columns

            .small-10.columns
              = f.input :email
          .row.collapse
            .small-2.columns
            .small-10.columns
              = f.input :first_name
          .row.collapse
            .small-2.columns
            .small-10.columns
              = f.input :last_name
          .row.collapse
            .small-2.columns

            .small-10.columns
              = f.input :password
          .row.collapse
            .small-2.columns

            .small-10.columns
              = f.input :password_confirmation
              = f.button :submit
          p
            | Already have an account?
            a href="#"  Login here &raquo

app/views/chefs/show.slim
h1 My confirmations
h2 Chef
=> link_to 'Make confirmation', reservations_path



#tabs
  ul
    li
      a href="#fragment-1"  Reservations
    li
      a href="#fragment-2"  Profile

  #fragment-1
    = render 'reservations/current_reservations_chef'
  #fragment-2
    = render 'home/profile'