config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/mobile'


  resources :users, :recipes
  post 'reservations/new' => 'charges/new', as: 'new_charge'

  get 'users/user_account'
  get 'users/my_reservations_user'
  get 'login_user' => 'sessions#new_user'

  get 'chefs/chef_account'
  # get 'chefs/my_reservations_chef'
  get 'login_chef' => 'sessions#new_chef'

  get 'messages/new'

  get 'reservations/new'

  post 'sessions/login_user'
  post 'sessions/login_chef'



  resources :reservations do
    resources :messages
  end
  get 'reservations/show'
  patch 'reservations/show'


  post 'chefs' => 'chefs#create'
  get 'chefs' => 'chefs#index', as: 'chefs_admin'
  get 'chefs/new' => 'chefs#new', as: 'new_chef'
  get 'chefs/:id/account' => 'chefs#show', as: 'chef'
  get 'chefs/:id/edit' => 'photos#edit', as: 'edit_chef'
  patch 'chefs/:id' => 'chefs#update'
  put 'chefs/:id' => 'chefs#update'
  delete 'chefs/:id' => 'chefs#destroy'
  get 'chefs/:id' => 'chefs#toggle', as: 'toggle_active_chef'

  get '/logout', to: 'sessions#destroy'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :reservations
  validates :title, presence: true
  attr_accessor :image

  mount_uploader :image, RecipeImageUploader # Tells rails to use this uploader for this model.



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :is_admin?, except: :index

  def index
    @recipes = Recipe.all.order('updated_at DESC')
  end
  def new
    @recipe = Recipe.new
    @image = params[:file]
  end
  def create
    @recipe = Recipe.new recipe_params
    @recipe.ingredients = recipe_params[:ingredients].strip.split(',')
    if @recipe.save
      redirect_to recipes_path, flash:{notice: 'recipe created'}
    else
      redirect_to :back, flash:{notice: 'there was an error'}
    end
  end
  def show
    @image = params[:file]
  end
  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.ingredients = JSON.parse(@recipe.ingredients).join(", ")
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, flash:{notice:"Recipe Destroyed"}
  end
  def update
    recipe = Recipe.find(params.require(:id))
    recipe.title = recipe_params[:title]
    recipe.recipe = recipe_params[:recipe]
    recipe.ingredients = recipe_params[:ingredients].strip.split(',')
    if recipe.save
      redirect_to recipes_path, flash:{notice:"Recipe Modified"}
    end
  end
  private
  def recipe_params
    params.
        require(:recipe).
        permit(:title, :ingredients, :recipe, :image)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_form.slim
.row
  .form-wrapper
    .large-6.columns
      .signup-panel
        p.welcome New Recipe
        = simple_form_for @recipe do |f|
          .row.collapse
            .small-10.columns
              = f.input :title
          .row.collapse
            .small-10.columns
              = f.input :ingredients
          .row.collapse
            .small-10.columns
              = f.input :recipe
          .row.collapse
            .small-10.columns
              = f.file_field :image
          .row.collapse
            .small-10.columns
              = f.button :submit

app/views/recipes/edit.slim
= render 'recipe_form'

app/views/recipes/index.slim
= div_for(@recipes, class: 'recipe') do |recipe|
  .recipe_title
    = recipe.title
    .admin_buttons
      - if is_admin?
        .destroy
          = link_to "Destroy", recipe, method: :delete, data: { confirm: "Are you sure you would like to destroy this recipe?" }
        .edit
          = link_to "Edit", edit_recipe_path(recipe)
  .recipe_image
    = image_tag( recipe.image, height: '300', width: '300')
  .recipe_ingredients
    = content_tag :div do
      -JSON.parse(recipe.ingredients).each_with_index do |item,index|
        p
          span
            = (index + 1).to_s + ' - '
          span
            =item
  .recipe_info
    = recipe.recipe
  hr

app/views/recipes/new.slim
= render 'recipe_form'