config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/mobile'


  resources :users, :recipes
  post 'reservations/new' => 'charges/new', as: 'new_charge'

  get 'users/user_account'
  get 'users/my_reservations_user'
  get 'login_user' => 'sessions#new_user'

  get 'chefs/chef_account'
  # get 'chefs/my_reservations_chef'
  get 'login_chef' => 'sessions#new_chef'

  get 'messages/new'

  get 'reservations/new'

  post 'sessions/login_user'
  post 'sessions/login_chef'



  resources :reservations do
    resources :messages
  end
  get 'reservations/show'
  patch 'reservations/show'


  post 'chefs' => 'chefs#create'
  get 'chefs' => 'chefs#index', as: 'chefs_admin'
  get 'chefs/new' => 'chefs#new', as: 'new_chef'
  get 'chefs/:id/account' => 'chefs#show', as: 'chef'
  get 'chefs/:id/edit' => 'photos#edit', as: 'edit_chef'
  patch 'chefs/:id' => 'chefs#update'
  put 'chefs/:id' => 'chefs#update'
  delete 'chefs/:id' => 'chefs#destroy'
  get 'chefs/:id' => 'chefs#toggle', as: 'toggle_active_chef'

  get '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reservations
  has_many :messages

  validates :first_name, :last_name, :email,  presence: true

  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i},
            uniqueness: true

  validates :phone,
            format: {with: /\A(1?(?: |\-|\.)?(?:\(\d{3}\)|\d{3})(?: |\-|\.)?\d{3}(?: |\-|\.)?\d{4})\z/,
                     message: "bad format ex. 555-555-5555"},
            allow_nil: true
  def self.auth_change(user,user_params)
    find_by(email: user[:email]).
        try(:authenticate, user_params[:old_password])
  end
  def name
    [first_name, last_name].join " "
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :require_user, only:[:edit,:show,:update]
  before_action :require_logged_in, except: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user , flash:{notice: 'created user and logged in'}
    else
      render action: 'new', flash:{notice:'please try again'}
    end
  end

  def edit
    @profile = current_user
  end

  def show
    @user_reservations = Reservation.user(current_user)
    @user_old_reservations = Reservation.user_old(current_user)
    @user = current_user
    @profile = @user
  end

  def update
    @user = User.auth_change(@user,user_params)
    if @user
      if @user.update_attributes(user_params.except(:old_password))
        redirect_to user_path, notice: 'User was successfully updated.'
      else
        redirect_to :back, notice: 'something went wrong'
      end
    else
      redirect_to :back, notice: 'Your old password was wrong'
    end
  end



  private
  def set_user
    @user = current_user

  end
  def user_params
    params.
        require(:user).
        permit(:email, :password,:first_name, :address, :address2, :last_name, :password_confirmation, :city, :state, :zip, :phone, :old_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profileuser.slim
.row
  .form-wrapper
    .large-6.columns
      .signup-panel
        = simple_form_for @user do |f|
          form
            .row.collapse
              .small-10.columns
                = f.input :email
            .row.collapse
              .small-10.columns
                = f.input :first_name
            .row.collapse
              .small-10.columns
                = f.input :last_name
            .row.collapse
              .small-10.columns
                = f.input :city
            .row.collapse
              .small-10.columns
                = f.input :state
            .row.collapse
              .small-10.columns
                = f.input :zip
            .row.collapse
              .small-10.columns
                = f.input :phone, as: :tel
            .row.collapse
              .small-10.columns
                = f.input :password
            .row.collapse
              .small-10.columns
                = f.input :password_confirmation
                = f.button :submit

app/views/users/_user.slim
.row
  .form-wrapper
    .large-6.columns
      .signup-panel
        p.welcome Your Account Details
        .row.collapse
          .small-10.columns
            h4 Email: #{@user.email}
        .row.collapse
          .small-10.columns
            h4 First Name: #{@user.first_name}
        .row.collapse
          .small-10.columns
            h4 Last Name: #{@user.last_name}
        .row.collapse
          .small-10.columns
            h4 Address: #{@user.address}
        .row.collapse
          .small-10.columns
            h4 Address: #{@user.address2}
        .row.collapse
          .small-10.columns
            h4 City: #{@user.city}
        .row.collapse
          .small-10.columns
            h4 Zip: #{@user.zip}
        .row.collapse
          .small-10.columns
            h4 Phone Number: #{@user.phone}
        .row.collapse
          .small-10.columns
            h4 Dietery Restrictions: #{@user.diet_restrictions}

app/views/users/admin.slim
h1 My Account
h2 Hi #{@user.first_name} User

/=> link_to 'New Reservation', new_reservation_path
/= link_to 'Edit Profile', edit_user_path(@user)

#tabs
  ul
    li
      a href="#fragment-1"  Reservations
    li
      a href="#fragment-2"  Profile

  #fragment-1

  #fragment-2
    = render 'home/profile'

app/views/users/edit.slim
= render 'home/profile'

app/views/users/new.slim
form
.row
  .large-4.columns
    label
      = simple_form_for @user do |f|
        = f.input :email
        = f.input :first_name
        = f.input :last_name
        = f.input :password
        = f.input :password_confirmation
        = f.submit 'Create User', :class => 'button'

p
  | Already have an account?
  == link_to "Login Here ", sessions_login_user_path
  
  

app/views/users/show.slim
h1 My Account
/= link_to 'Edit Profile', edit_user_path(@user)
h2 Hi #{@user.first_name} User

/=> link_to 'New Reservation', new_reservation_path
/= link_to 'Edit Profile', edit_user_path(@user)
/= render 'reservations/current_reservations_user'
/= render 'reservations/old_reservations_user'
#tabs
  ul
    li
      a href="#fragment-1"  Current Reservations
    li
      a href="#fragment-2"  Profile
    li
      a href="#fragment-2"  Past Reservations

  #fragment-1
    = render 'reservations/current_reservations_user'
  #fragment-2
    = render 'home/profile'
  #fragment-2
    = render 'reservations/old_reservations_user'