config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/mobile'


  resources :users, :recipes
  post 'reservations/new' => 'charges/new', as: 'new_charge'

  get 'users/user_account'
  get 'users/my_reservations_user'
  get 'login_user' => 'sessions#new_user'

  get 'chefs/chef_account'
  # get 'chefs/my_reservations_chef'
  get 'login_chef' => 'sessions#new_chef'

  get 'messages/new'

  get 'reservations/new'

  post 'sessions/login_user'
  post 'sessions/login_chef'



  resources :reservations do
    resources :messages
  end
  get 'reservations/show'
  patch 'reservations/show'


  post 'chefs' => 'chefs#create'
  get 'chefs' => 'chefs#index', as: 'chefs_admin'
  get 'chefs/new' => 'chefs#new', as: 'new_chef'
  get 'chefs/:id/account' => 'chefs#show', as: 'chef'
  get 'chefs/:id/edit' => 'photos#edit', as: 'edit_chef'
  patch 'chefs/:id' => 'chefs#update'
  put 'chefs/:id' => 'chefs#update'
  delete 'chefs/:id' => 'chefs#destroy'
  get 'chefs/:id' => 'chefs#toggle', as: 'toggle_active_chef'

  get '/logout', to: 'sessions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, :set_chef
  def index
    @recipes = Recipe.all
  end

  def mobile
    @reservations = Reservation.all
  end
  private
  def set_user
    if current_user
      @user ||= current_user
    end
  end
  def set_chef
    if current_chef
      @chef ||= current_chef
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def no_one_logged_in?
    not someone_logged_in?
  end

  def someone_logged_in?
    current_user or current_chef
  end

  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end
  #
  # def current_chef
  #   @current_chef ||= Chef.find_by(id: session[:chef_id])
  # end
  # def is_logged_in
  #   current_chef || current_user
  # end
  # def is_admin?
  #   (current_user && current_user.email == 'admin@admin.com') ? true : false
  # end
  # def chef_active?
  #   current_chef.active?
  # end

  # def active_if_current_page(path)  ##### , class: (active_if_current_page(new_user_path)
  #   current_page?(path) ? 'active' : ''
  # end

  # def item_list(items)   #########
  #   content_for(:head, javascript_include_tag 'bootstrap')
  #   html = "<div><ul>".html_safe
  #   items.each do |item|
  #     html += "<li>".html_safe + item.name + "</li>".html_safe
  #   end
  #   html += "</ul></div>".html_safe
  #   html
  # end

end

app/views/home/_navbar.slim
/ nav.menu
  / = link_to 'Cookio', root_path
  = render 'sessions/user_login'
  /.sidebar
  /  #hamburger
  /    .slice
  /    .slice
  /    .slice
  /  section
  /    ul#menu-list
  /      li
  /        == link_to 'Mobile', home_mobile_path
  /      -if no_one_logged_in?
  /        li
  /          == link_to 'New User', new_user_path
  /        li
  /          == link_to 'New Chef', new_chef_path
  /        li
  /          == link_to 'Chef Login', login_chef_path
  /        li
  /          == link_to 'User Login', login_user_path
  /      -if current_user
  /        li
  /          == link_to 'New Reservation', reservations_new_path
  /      -if current_chef
  /        li
  /          == link_to 'Reservations', reservations_path
  /      -if someone_logged_in?
  /        li
  /          == link_to 'My Account', (@chef || @user)
  /        li
  /          == link_to 'Sign Out', logout_path
  /        li
  /          == link_to 'Mobile', home_mobile_path
/ ul#menu-list
/   /li
/     /== link_to 'Mobile', home_mobile_path
/   -if is_admin?
/     li
/       => link_to 'admin', recipes_path
/     li
/       = link_to 'new recipe', new_recipe_path
/     li
/       = link_to 'Chefs', chefs_path
/   -if no_one_logged_in?
/     li
/       == link_to 'New User', new_user_path
/     li
/       == link_to 'New Chef', new_chef_path
/     li
/       == link_to 'Chef Login', login_chef_path
/     li
/       == link_to 'User Login', login_user_path
/   -if !is_admin? && current_user
/     li
/       == link_to 'New Reservation', reservations_new_path
/   -if current_chef
/     li
/       == link_to 'Reservations', reservations_path
/   -if someone_logged_in?
/     -if not is_admin?
/       li
/         == link_to 'My Account', (@chef || @user)
/     li
/       == link_to 'Sign Out', logout_path

nav.top-bar data-topbar="" role="navigation" 
  ul.title-area
    li.name
      h1
        = link_to 'Cookio', root_path
    /! Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    li.toggle-topbar.menu-icon
      a href="#" 
        span Menu
  section.top-bar-section
    /! Right Nav Section
    ul.right
      -if is_admin?
        li
          => link_to 'admin', recipes_path
        li
          = link_to 'new recipe', new_recipe_path
        li
          = link_to 'Chefs', chefs_path
      -if no_one_logged_in?
        li
          == link_to 'New User', new_user_path
        li
          == link_to 'New Chef', new_chef_path
        li
          == link_to 'Chef Login', login_chef_path
        li
          == link_to 'User Login', login_user_path
      -if !is_admin? && current_user
        li
          == link_to 'New Reservation', reservations_new_path
      -if current_chef
        li
          == link_to 'Reservations', reservations_path
      -if someone_logged_in?
        -if not is_admin?
          li
            == link_to 'My Account', (@chef || @user)
        li
          == link_to 'Sign Out', logout_path
    /! Left Nav Section
    ul.left
      li
        a href="#"  Left Nav Button
 





span
  = notice

app/views/home/_profile.slim
.row
  .form-wrapper
    .large-6.columns
      .signup-panel
        = simple_form_for @profile do |f|
          form
            .row.collapse
              .small-10.columns
                = f.input :email
            .row.collapse
              .small-10.columns
                = f.input :first_name
            .row.collapse
              .small-10.columns
                = f.input :last_name
            .row.collapse
              .small-10.columns
                = f.input :address
            .row.collapse
              .small-10.columns
                = f.input :address2
            .row.collapse
              .small-10.columns
                = f.input :city
            .row.collapse
              .small-10.columns
                = f.input :state
            .row.collapse
              .small-10.columns
                = f.input :zip
            .row.collapse
              .small-10.columns
                = f.input :phone, as: :tel
            .row.collapse
              .small-10.columns
                = f.input :password
            .row.collapse
              .small-10.columns
                = f.input :password_confirmation
            .row.collapse
              .small-10.columns
                = f.input :old_password
            .row.collapse
              .small-10.columns
                = f.button :submit

app/views/home/index.slim
.index-photo
  = image_tag('http://i.huffpost.com/gen/1475945/images/o-COOKING-AT-HOME-facebook.jpg')
.index-photo
  = image_tag('https://s3.amazonaws.com/cookie-pics/how_do_you_cookio.png')

.become-a-chef
  p Become a Chef! #{link_to 'Click Here', new_chef_path}
.make-a-reservation
  - if current_user
    = link_to 'Make a Reservation', new_reservation_path
  - elsif current_chef
    = link_to 'All Reservations', reservations_path
- @recipes.each do |r|
  - if current_user
    = link_to image_tag( r.image, height: '300', width: '300' ), new_reservation_path(r.id)
  - else
    = link_to image_tag(r.image, height: '300', width: '300'), login_user_path

app/views/home/mobile.slim
.wrapper.cards
  .container
    .card
      .front
        h2 Roast Chicken Meal
      .back
        .content
          h3.cardTitle Roast Chicken Dinner
          p User: Ben Shelomovitz
          p Date: 12/2/2018
          p Time: 8:00pm
          p Location: 123 Center Way, Miami FL 33123
          p Number of plates: 3
          p Details: I would like the meal to be kosher
          p Messages:
          p Chef: sure
          p Ben: Thanks!
          p Chef: sure
          p Ben: Thanks!


- @reservations.each do |r|
  .wrapper.cards
    .container
      .card
        .front
          h2 #{r.recipe.title} Meal
        .back
          .content
            h3.cardTitle #{r.recipe.title} Meal
            p Customer: #{r.user.name}
            p Date: #{r.date}
            p Time: #{r.time}
            p Location: #{r.address + " " + r.address2}
            p Number of plates: #{r.plates}
            p Details: #{r.details}
            .reserve
            /  - if current_chef && r.chef_id != current_chef.id
            /    = link_to "reserve", r, method: :patch
            /h3 Messages:
            /= render 'reservations/message'
            /- if r.chef_id
            /  = simple_form_for ([r, @new_reservations_message]) do |f|
            /    = f.input :subject
            /    = f.input :message
            /    = f.submit